"""Create initial tables

Revision ID: 0ff973566f8a
Revises: 
Create Date: 2025-03-13 12:36:08.713383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff973566f8a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'CLAIMED', 'DOWNLOADING', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'RETRYING', 'CANCELED', name='jobstate'), nullable=False),
    sa.Column('media_url', sa.String(), nullable=False),
    sa.Column('media_sha256', sa.String(length=64), nullable=True),
    sa.Column('processing_mode', sa.Enum('DOWNMIX', 'SELECT', 'MULTITRACK', name='processingmode'), nullable=False),
    sa.Column('track_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('error_history', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('media_duration_seconds', sa.Float(), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_state'), 'jobs', ['state'], unique=False)
    op.create_index(op.f('ix_jobs_tenant_id'), 'jobs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_tenant_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_state'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
